# Generated by Django 5.0.4 on 2024-05-15 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.FloatField()),
                ("deadline", models.DateField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("missed", "Missed"),
                            ("paid", "Paid"),
                            ("paid_late", "Paid late"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("credit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="credit.credit")),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_payments", to="payment.payment"
                    ),
                ),
            ],
        ),
    ]
