# Generated by Django 5.0.4 on 2024-04-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("credit", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="credit.credit")),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
    ]
