# Generated by Django 5.0.4 on 2024-05-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="deadline",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("missed", "Missed"), ("paid", "Paid"), ("paid_late", "Paid late")],
                default="pending",
                max_length=30,
            ),
        ),
    ]
