# Generated by Django 5.0.4 on 2024-05-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_remove_payment_user_userpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpayment",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_payments", to="payment.payment"
            ),
        ),
    ]
