# Generated by Django 5.0.4 on 2024-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("-id",)},
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(help_text="User Email", max_length=64, unique=True),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
