# Generated by Django 5.0.4 on 2024-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_remove_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="risk",
            field=models.FloatField(default=0.1),
        ),
    ]
