# Generated by Django 5.0.4 on 2024-05-12 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("rate", models.DecimalField(decimal_places=5, max_digits=20)),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("min_term_months", models.IntegerField()),
                ("max_term_months", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("term_months", models.IntegerField()),
                ("purpose", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("waiting", "Waiting for Approval"),
                            ("rejected", "Rejected"),
                            ("ongoing", "Ongoing"),
                            ("paid", "Paid"),
                            ("written_off", "Written off"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("general_expenses", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                (
                    "credit_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="credit.credittype"),
                ),
            ],
            options={
                "ordering": ("-id",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserCredit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("credit", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="credit.credit")),
            ],
        ),
    ]
