# Generated by Django 5.0.4 on 2024-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="general_expenses",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
