# Generated by Django 5.0.4 on 2024-06-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="net_comprehended_income",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="credit",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("waiting", "Waiting for Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("ongoing", "Ongoing"),
                    ("paid", "Paid"),
                    ("written_off", "Written off"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
