# Generated by Django 5.0.4 on 2024-05-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for Approval"),
                    ("rejected", "Rejected"),
                    ("ongoing", "Ongoing"),
                    ("paid", "Paid"),
                    ("written_off", "Written off"),
                ],
                default="waiting",
                max_length=30,
            ),
        ),
    ]
