# Generated by Django 5.0.4 on 2024-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0003_alter_credit_general_expenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="credit",
            name="general_expenses",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
