# Generated by Django 5.0.4 on 2024-05-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0003_credit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
