# Generated by Django 5.0.4 on 2024-05-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0004_alter_credit_amount_alter_credit_general_expenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercredit",
            name="credit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_credits", to="credit.credit"
            ),
        ),
    ]
